#!/bin/sh /etc/rc.common
START=100

ser2net()
{
    local enabled
    config_get_bool enabled $1 enabled

    if [ $enabled ]; then
#        /etc/init.d/ser2net_server stop
        local srvmode
        config_get srvmode $1 srvmode
        echo $srvmode
        if [ "$srvmode"x = "0"x ]; then
            echo $srvmode
            killall /bin/ser2net_server
            pidof ser2net_client | awk '{print $2}' > /tmp/ser2net_client
            PID=$(cat /tmp/ser2net_client)
            rm /tmp/ser2net_client
            if [ ! $PID ]; then
                echo "ser2net client has started."
                /bin/ser2net_client &
            else
                echo "ser2net client: is already running"
            fi
        else
            echo $srvmode
            killall /bin/ser2net_client
            pidof ser2net_server | awk '{print $2}' > /tmp/ser2net_server
            PID=$(cat /tmp/ser2net_server)
            rm /tmp/ser2net_server
            if [ ! $PID ]; then
                echo "ser2net server has started."
                /bin/ser2net_server &
            else
                echo "ser2net server: is already running"
            fi
        fi
    fi
}

start()
{
    config_load ser2net
    config_foreach ser2net ser2net
}

stop()
{
#    pidof ser2net_client | sed -e "s/$$//g" > /tmp/ser2net_client_pid
#    PID=`cat /tmp/ser2net_client_pid`
#    rm -f /tmp/ser2net_client_pid
#    kill -9 $PID
    echo "ser2net client has stoped."
    echo "ser2net server has stoped."
    killall /bin/ser2net_client
    killall /bin/ser2net_server
}