#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set fstab.@global[0].anon_mount=1
uci commit fstab

# sed -i -e "/option device 'br-lan'/a\ \toption ifname 'br-lan'" /etc/config/network
# sed -i -e "/option device 'wan'/a\ \toption ifname 'wan'" /etc/config/network

rm -f /usr/lib/lua/luci/view/admin_status/index/mwan.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/upnp.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/ddns.htm
rm -f /usr/lib/lua/luci/view/admin_status/index/minidlna.htm

sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/aria2.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/hd_idle.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/samba4.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/minidlna.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/transmission.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/mjpg-streamer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/p910nd.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/usb_printer.lua
sed -i 's/\"services\"/\"nas\"/g' /usr/lib/lua/luci/controller/xunlei.lua
sed -i 's/services/nas/g'  /usr/lib/lua/luci/view/minidlna_status.htm
sed -i 's/services/nas/g' /usr/lib/lua/luci/view/aria2/overview_status.htm
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-aria2.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-hd_idle.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-samba.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-samba4.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-minidlna.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-transmission.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-p910nd.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-usb_printer.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-xunlei.json
sed -i 's/services/nas/g' /usr/share/luci/menu.d/luci-app-mjpg-streamer.json

ln -sf /sbin/ip /usr/bin/ip

sed -i 's#downloads.openwrt.org#mirrors.cloud.tencent.com/openwrt#g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh

sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

echo 'hsts=0' > /root/.wgetrc

sed -i -e "/--color=auto/aPS1='\\\\[\\\\e[32m\\\\][\\\\[\\\\e[m\\\\]\\\\[\\\\e[31m\\\\]\\\\u\\\\[\\\\e[m\\\\]\\\\[\\\\e[33m\\\\]@\\\\[\\\\e[m\\\\]\\\\[\\\\e[32m\\\\]\\\\h\\\\[\\\\e[m\\\\]:\\\\[\\\\e[m\\\\]\\\\[\\\\e[32m\\\\]\\\\[\\\\e[1;32m\\\\]\\\\@\\\\[\\\\e[36m\\\\] \\\\w\\\\[\\\\e[m\\\\]\\\\[\\\\e[32m\\\\]]\\\\[\\\\e[0m\\\\] \\\\$\\\\[\\\\e[m\\\\] '" /etc/shinit
sed -i -e "/--color=auto/aalias reboot='(/bin/busybox reboot &);sleep 3;/bin/busybox reboot -f'" /etc/shinit

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

chmod 0755 /etc/init.d/*
chmod 0755 /usr/share/passwall3/*.sh /usr/share/passwall3/*.lua

rm -f /etc/uci-defaults/zzz-default-settings

exit 0
