#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@alist[-1]
	add ucitrack alist
	set ucitrack.@alist[-1].init=alist
	commit ucitrack
EOF

chmod +x /etc/init.d/alist >/dev/null 2>&1

rm -rf /tmp/luci-*
exit 0
