#!/bin/sh

[[ "$ACTION" == "ifup" && "$INTERFACE" == "wan" && $(uci get "passwall3.@global[0].enabled") == "1" ]] && {
    /etc/init.d/passwall3 restart
    echo "passwall3: restart when wan ifup" > /dev/kmsg
}

